version: '2'
services:
    heardapp-app:
        image: heardapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://heardapp-postgresql:5432/heardApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    heardapp-postgresql:
        extends:
            file: postgresql.yml
            service: heardapp-postgresql
